language: go

sudo: false

go:
  - tip

install:
  - go get -u ./...
  - go get -u github.com/Akagi201/light
  - go get -u github.com/stretchr/testify/assert

script:
  - go test -v -bench=. -benchmem -cover ./...
